### ISSUE TITLE
Printer wont connect after PrintJobHistory 1.17.1

### ISSUE THREAD

**Issue by jp-phys-NEIU** [dojohnso/OctoPrint-PrintJobHistory#6]
Printer (Creality CR10S Pro, original firmware) and Octprint worked yesterday. Upgraded PrintJobHistory 1.17.1 this morning. Now, Octoprint refuses to connect to printer, gives 'Failed to enable Bed Leveling' error. I cycle power, relevel bed & reset Z offset. Octoprint still refuses. After disabling Firmware Check and PrintJobHistory, and restart Octorprint, it still won't connect. I'm back to printing off SD card. Maybe this is a coincidence, I don't know, but after 3 years on Octoprint, no longer works.

**Comment by dojohnso** [comment]
@jp-phys-NEIU - This is weird. The update only changed a couple things around thumbnails and ownership references, it shouldn't have affected anything around printer connection. You mentioned you disabled PrintJobHistory. Can you try uninstalling it outright? I know you'll probably lose the history though, so up to you. 

Is there anything in the octoprint logs? I wonder if something else didn't update when you updated this plugin. Is it possible to try a fresh install of octoprint? or start it up in safe mode and see if that helps?

**Comment by jp-phys-NEIU** [comment]
I restarted in safe mode, same results. There might be a hardware issue with my printer USB port, or the motherboard. It prints OK from SD card, but as of yesterday, Octoprint on rPi can't connect to printer, because of 'Failed to enable Bed Leveling' error. I enable or disable bed leveling on the printer, makes no difference.
**PrintJobHistory might not be at fault**, though the bug surfaced after the upgrade & subsequent Octoprint restart. I will check out reddit & other resources. Thanks for your attention!

**Comment by dojohnso** [comment]
Oof that sucks. Hopefully it's nothing too serious! Sounds like it's a coincidence with this update but I'll keep this issue open for a minute just in case. Let me know if there's anything I can do or if you find out anything useful. Good luck!

**Comment by jp-phys-NEIU** [comment]
Yes, it's looking like a hardware glitch. You can close the issue. Thanks!

**Comment by dojohnso** [comment]
Ok thanks for letting me know. And good luck!
