### ISSUE TITLE
Print job history discards transparent background of original PNGs

### ISSUE THREAD

**Issue by eschreiner** [dojohnso/OctoPrint-PrintJobHistory#7]
First of all, @dojohnso thank you so much for working on this plugin!

When viewing the print job history with a dark theme, the embedded images (@dojohnso thank you for fixing this!!!) are converted to JPGs with white background.

![grafik](https://github.com/dojohnso/OctoPrint-PrintJobHistory/assets/184471/8a42bdab-6eb5-4045-9157-b8892fb2b15e)

(am using Octoprint in German)

Not a big deal, but would be a nice improvement.

Best regards!

**Comment by dojohnso** [comment]
@eschreiner thanks again for this. I've pushed a fix in the pre-release channel if you're interested in checking it out. I'll likely push it out to production later today or tomorrow.

**Comment by eschreiner** [comment]
have just installed the DEV version - much better! Thank you so much!

![grafik](https://github.com/dojohnso/OctoPrint-PrintJobHistory/assets/184471/6d6b2e7c-0b26-436f-8a30-a1fe78fffce7)
